apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: cluster-down
spec:
  hostCollectors:
    - run:
        collectorName: "cni"
        command: "find"
        args: ["/etc/cni/net.d/", "-type", "f", "-exec", "tail", "-v", "-n", "+1", "{}", "\\;"]
