apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: cni-conf
spec:
  collectors:
    - copyFromHost:
        collectorName: "cni"
        image: busybox:1
        hostPath: /etc/cni/net.d/
        extractArchive: true
  hostCollectors:
    - run:
        collectorName: "cni"
        name: "tail-cni"
        command: "sh"
        args: ["-c", "tail -v -n +1 /etc/cni/net.d/*.conflist"]
    - run:
        collectorName: "cni"
        name: "ls-cni
        command: "ls"
        args: ["-lha", "/etc/cni/net.d/"]
  analyzers:
    - textAnalyze:
        checkName: "Check for CNI 'not ready' messages"
        fileName: host-collectors/run-host/journalctl-kubelet.txt
        regex: "Container runtime network not ready.*cni plugin not initialized"
        outcomes:
          - pass:
              when: "false"
              message: "CNI is initialized"
          - fail:
              when: "true"
              message: "CNI plugin not initialized: there may be a problem with the CNI configuration on the host, check /etc/cni/net.d/*.conflist against a known good configuration"
